import { expect, test, type Page } from '@playwright/test'

type Rect = { x: number; y: number; width: number; height: number }

function right(rect: Rect): number {
  return rect.x + rect.width
}

function bottom(rect: Rect): number {
  return rect.y + rect.height
}

function intersectionArea(first: Rect, second: Rect): number {
  const width = Math.max(0, Math.min(right(first), right(second)) - Math.max(first.x, second.x))
  const height = Math.max(0, Math.min(bottom(first), bottom(second)) - Math.max(first.y, second.y))
  return width * height
}

async function chooseScenarioAndAdvance(page: Page, scenario: 'closed' | 'sparse' | 'colonization'): Promise<void> {
  await page.locator(`[data-scenario="${scenario}"]`).click()
  await page.locator('#wizard-next').click()
}

async function finishSetup(page: Page): Promise<void> {
  await page.locator('#wizard-next').click()
  await page.locator('[data-strategy="sun"]').click()
  await page.locator('#wizard-next').click()
  await page.locator('[data-species]:visible').first().click()
  await page.locator('#wizard-next').click()
  await page.locator('#start-game').click()
}

test('five-step setup previews density and opens the guided forest UI', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('pageerror', (error) => browserErrors.push(error.message))

  await page.goto('/')
  await expect(page.locator('#setup-wizard')).toBeVisible()
  await expect(page.locator('#wizard-progress')).toContainText('1 / 5')
  await chooseScenarioAndAdvance(page, 'closed')

  await expect(page.locator('#wizard-progress')).toContainText('2 / 5')
  await expect(page.locator('#density-slider')).toBeVisible()
  await expect(page.locator('#density-input')).toHaveValue('30')
  await expect(page.locator('#density-total')).toContainText('750 个体')
  await page.locator('#density-input').fill('40')
  await expect(page.locator('#density-total')).toContainText('1,000 个体')

  await finishSetup(page)
  await expect(page.locator('#tutorial-modal')).toBeVisible()
  await page.locator('#tutorial-skip').click()
  await expect(page.locator('#tutorial-modal')).toBeHidden()

  await expect(page.locator('#game-root canvas')).toBeVisible()
  await expect(page.locator('#map-scale-overlay')).toBeVisible()
  await expect(page.locator('#map-x-tick-0')).toHaveText('0')
  await expect(page.locator('#map-x-tick-4')).toHaveText('100')
  await expect(page.locator('.simulation-controls')).toBeVisible()
  await expect(page.locator('#pause-button')).toHaveText('开始演替')
  await expect(page.locator('.allocation-panel')).toBeVisible()
  const mapBox = await page.locator('#game-root').boundingBox()
  const controlsBox = await page.locator('.simulation-controls').boundingBox()
  const allocationBox = await page.locator('.allocation-panel').boundingBox()
  const mapWindowBox = await page.locator('[data-panel-id="map"]').boundingBox()
  const strategyWindowBox = await page.locator('[data-panel-id="strategy"]').boundingBox()
  const statisticsWindowBox = await page.locator('[data-panel-id="statistics"]').boundingBox()
  const workspaceBox = await page.locator('#workspace-root').boundingBox()
  expect(mapBox).not.toBeNull()
  expect(controlsBox).not.toBeNull()
  expect(allocationBox).not.toBeNull()
  expect(mapWindowBox).not.toBeNull()
  expect(strategyWindowBox).not.toBeNull()
  expect(statisticsWindowBox).not.toBeNull()
  expect(workspaceBox).not.toBeNull()
  expect(mapWindowBox!.width / workspaceBox!.width).toBeGreaterThan(0.53)
  expect(controlsBox!.y).toBeGreaterThanOrEqual(mapBox!.y + mapBox!.height - 2)
  expect(strategyWindowBox!.x).toBeGreaterThan(mapWindowBox!.x + mapWindowBox!.width - 2)
  expect(statisticsWindowBox!.x).toBeGreaterThan(mapWindowBox!.x + mapWindowBox!.width - 2)
  expect(statisticsWindowBox!.y).toBeLessThan(strategyWindowBox!.y)
  expect(statisticsWindowBox!.height / workspaceBox!.height).toBeGreaterThan(0.59)
  expect(allocationBox!.y).toBeGreaterThanOrEqual(strategyWindowBox!.y)

  await page.locator('#game-root canvas').hover({ position: { x: mapBox!.width / 2, y: mapBox!.height / 2 } })
  await page.mouse.wheel(0, -500)
  await expect(page.locator('#map-x-tick-0')).not.toHaveText('0')
  await page.locator('#reset-map-button').click()
  await expect(page.locator('#map-x-tick-0')).toHaveText('0')

  await page.locator('#pause-button').click()
  await expect(page.locator('#pause-button')).toHaveText('暂停')
  await page.locator('[data-speed="4"]').click()
  await expect(page.locator('[data-speed="4"]')).toHaveClass(/active/)
  await page.screenshot({ path: testInfo.outputPath('forest-game.png'), fullPage: true })

  await page.locator('#properties-button').click()
  await expect(page.locator('#properties-drawer')).toBeVisible()
  await expect(page.locator('#property-summary')).toContainText('密度')
  await expect(page.locator('#property-summary')).toContainText('平均胸径')
  await expect(page.locator('#property-summary')).toContainText('胸高断面积')
  await expect(page.locator('#property-page-status')).toBeVisible()
  const visibleRows = await page.locator('#property-table-body tr').count()
  expect(visibleRows).toBeGreaterThan(0)
  expect(visibleRows).toBeLessThanOrEqual(150)

  expect(browserErrors).toEqual([])
})

test('fixed GIS dashboard keeps layers outside the map and core controls compact', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('forest-tutorial-completed', 'true'))
  await page.goto('/')
  await chooseScenarioAndAdvance(page, 'sparse')
  await finishSetup(page)
  await expect(page.locator('#game-root canvas')).toBeVisible()

  const layerSidebar = page.locator('#layer-sidebar')
  const mapCanvas = page.locator('#game-root')
  const strategyPanel = page.locator('[data-panel-id="strategy"]')
  const statisticsPanel = page.locator('[data-panel-id="statistics"]')
  await expect(layerSidebar).toBeVisible()
  await expect(strategyPanel).toBeVisible()
  await expect(statisticsPanel).toBeVisible()

  const layerBox = await layerSidebar.boundingBox()
  const canvasBox = await mapCanvas.boundingBox()
  const strategyBox = await strategyPanel.boundingBox()
  const statisticsBox = await statisticsPanel.boundingBox()
  expect(layerBox).not.toBeNull()
  expect(canvasBox).not.toBeNull()
  expect(strategyBox).not.toBeNull()
  expect(statisticsBox).not.toBeNull()
  expect(layerBox!.width).toBeLessThanOrEqual(210)
  expect(right(layerBox!)).toBeLessThanOrEqual(canvasBox!.x + 2)
  expect(intersectionArea(layerBox!, canvasBox!)).toBe(0)
  expect(intersectionArea(canvasBox!, strategyBox!)).toBe(0)
  expect(intersectionArea(canvasBox!, statisticsBox!)).toBe(0)
  expect(canvasBox!.width).toBeGreaterThanOrEqual(520)
  expect(canvasBox!.height).toBeGreaterThanOrEqual(520)

  await expect(page.locator('#layer-tree')).toBeVisible()
  expect(await page.locator('#layer-tree').evaluate((element) => (element as HTMLDetailsElement).open)).toBe(true)
  await page.locator('[data-layer-key="stage:seedling"]').scrollIntoViewIfNeeded()
  await expect(page.locator('[data-layer-key="stage:seedling"]')).toBeVisible()
  for (const key of ['grid', 'subgrid', 'axes', 'individuals', 'player', 'stage:seed', 'stage:seedling', 'stage:sapling', 'stage:adult', 'selected', 'disturbance']) {
    await expect(page.locator(`[data-layer-key="${key}"]`)).toHaveCount(1)
  }
  await expect(page.locator('[data-layer-key="risk"]')).not.toBeChecked()
  await expect(page.locator('[data-layer-key="death"]')).not.toBeChecked()
  await expect(page.locator('.map-functional-legend')).toContainText('喜阳先锋型')
  await expect(page.locator('.map-functional-legend')).toContainText('耐荫型')
  await expect(page.locator('.map-functional-legend')).toContainText('广适型')
  await expect(page.locator('[data-species-layer]')).toHaveCount(6)
  for (let index = 0; index < 6; index += 1) await page.locator('#map-zoom-in').click()
  const detailHint = page.locator('.detail-layer-anchor #detail-layer-hint')
  await expect(detailHint).toBeVisible()
  const hintBox = await detailHint.boundingBox()
  const detailLayerBox = await page.locator('#layer-sidebar').boundingBox()
  expect(hintBox).not.toBeNull()
  expect(detailLayerBox).not.toBeNull()
  expect(hintBox!.x).toBeGreaterThanOrEqual(detailLayerBox!.x)
  expect(hintBox!.x + hintBox!.width).toBeLessThanOrEqual(detailLayerBox!.x + detailLayerBox!.width + 1)
  await page.locator('#dismiss-detail-layer-hint').click()
  await expect(detailHint).toBeHidden()
  await page.locator('#reset-map-button').click()
  const eventStripBox = await page.locator('.map-event-strip').boundingBox()
  const eventMessageBox = await page.locator('#event-message').boundingBox()
  expect(eventStripBox).not.toBeNull()
  expect(eventMessageBox).not.toBeNull()
  expect((eventMessageBox!.x - eventStripBox!.x) / eventStripBox!.width).toBeLessThan(0.32)
  await page.locator('[data-player-color="#87d8ff"]').click()
  await page.locator('[data-marker-size="large"]').click()
  expect(await page.evaluate(() => localStorage.getItem('forest-map-style-v1'))).toContain('#87d8ff')
  await page.locator('#reset-player-style').click()
  await expect(page.locator('#player-color-picker')).toHaveValue('#ffffff')

  await expect(page.locator('[data-statistics-panel]')).toHaveCount(0)
  await expect(page.locator('#statistics-launch-button')).toHaveCount(0)
  const statisticsBeforeExpand = await page.locator('[data-panel-id="statistics"]').boundingBox()
  const strategyBeforeExpand = await page.locator('[data-panel-id="strategy"]').boundingBox()
  const mapBeforeExpand = await page.locator('[data-panel-id="map"]').boundingBox()
  await page.locator('#expand-statistics-button').click()
  await expect(page.locator('[data-panel-id="statistics"]')).toHaveAttribute('data-maximized', '')
  await expect(page.locator('#expand-statistics-button')).toHaveText('恢复布局')
  const statisticsAfterExpand = await page.locator('[data-panel-id="statistics"]').boundingBox()
  expect(statisticsBeforeExpand).not.toBeNull()
  expect(strategyBeforeExpand).not.toBeNull()
  expect(mapBeforeExpand).not.toBeNull()
  expect(statisticsAfterExpand).not.toBeNull()
  expect(Math.abs(statisticsAfterExpand!.x - statisticsBeforeExpand!.x)).toBeLessThan(2)
  expect(Math.abs(statisticsAfterExpand!.width - statisticsBeforeExpand!.width)).toBeLessThan(2)
  expect(statisticsAfterExpand!.height).toBeGreaterThan(statisticsBeforeExpand!.height + strategyBeforeExpand!.height * 0.8)
  expect(statisticsAfterExpand!.x).toBeGreaterThanOrEqual(mapBeforeExpand!.x + mapBeforeExpand!.width - 2)
  await page.locator('#expand-statistics-button').click()
  await expect(page.locator('[data-panel-id="statistics"]')).not.toHaveAttribute('data-maximized', '')
  await expect(page.locator('#expand-statistics-button')).toHaveText('放大查看')
  await page.locator('#chart-mode-menu').click()
  await expect(page.locator('.chart-menu-popover')).toBeVisible()
  const chartMenuBackground = await page.locator('.chart-menu-popover').evaluate((element) => getComputedStyle(element).backgroundColor)
  expect(chartMenuBackground).toMatch(/rgb\((24[0-9]|25[0-5]),/)
  const chartTitleFontSize = parseFloat(await page.locator('#chart-title').evaluate((element) => getComputedStyle(element).fontSize))
  for (const selector of ['#statistics-detail > span', '#chart-mode-menu > summary', '.chart-menu-popover strong', '.chart-menu-popover button']) {
    const fontSize = parseFloat(await page.locator(selector).first().evaluate((element) => getComputedStyle(element).fontSize))
    expect(Math.abs(fontSize - chartTitleFontSize)).toBeLessThan(0.1)
  }
  const chartMenuScroll = await page.locator('.chart-menu-popover').evaluate((element) => ({
    clientHeight: element.clientHeight,
    scrollHeight: element.scrollHeight,
    overflowY: getComputedStyle(element).overflowY,
  }))
  expect(chartMenuScroll.overflowY).toBe('scroll')
  expect(chartMenuScroll.scrollHeight).toBeGreaterThan(chartMenuScroll.clientHeight)
  await page.locator('.chart-menu-popover').evaluate((element) => { element.scrollTop = element.scrollHeight })
  const chartMenuBox = await page.locator('.chart-menu-popover').boundingBox()
  const lastChartOptionBox = await page.locator('[data-chart-mode="selected"]').boundingBox()
  expect(chartMenuBox).not.toBeNull()
  expect(lastChartOptionBox).not.toBeNull()
  expect(lastChartOptionBox!.y + lastChartOptionBox!.height).toBeLessThanOrEqual(chartMenuBox!.y + chartMenuBox!.height + 1)
  await page.locator('[data-chart-mode="selected"]').click()
  await expect(page.locator('#chart-mode-label')).toHaveText('选中对象')
  await page.locator('#chart-mode-menu').click()
  await page.locator('[data-chart-mode="composition"]').click()
  await expect(page.locator('#chart-mode-menu')).toContainText('物种组成')
  await page.locator('#chart-mode-select').selectOption('composition')
  await expect(page.locator('#chart-title')).toContainText('群落物种组成')
  await page.locator('#chart-mode-select').selectOption('carbon')
  await expect(page.locator('#chart-title')).toContainText('游戏碳单位')
  await page.locator('#chart-mode-select').selectOption('species-abundance')
  await expect(page.locator('#chart-title')).toContainText('各物种个体数')
  await page.locator('#chart-mode-select').selectOption('functional-demography-counts')
  await expect(page.locator('#chart-title')).toContainText('出生与死亡个体')
  const demographyLegend = await page.evaluate(() => {
    const instance = (window as Window & { __forestChart: import('echarts').ECharts }).__forestChart
    const option = instance.getOption() as { series: Array<{ name: string }>; legend: Array<{ selected?: Record<string, boolean> }> }
    const deathName = option.series.find((series) => series.name.includes('死亡'))!.name
    instance.dispatchAction({ type: 'legendToggleSelect', name: deathName })
    return { deathName, selected: (instance.getOption().legend as Array<{ selected?: Record<string, boolean> }>)[0].selected?.[deathName] }
  })
  expect(demographyLegend.deathName).toContain('虚线')
  expect(demographyLegend.selected).toBe(false)
  await page.waitForTimeout(1_100)
  const deathLegendStillHidden = await page.evaluate((deathName) => {
    const instance = (window as Window & { __forestChart: import('echarts').ECharts }).__forestChart
    return (instance.getOption().legend as Array<{ selected?: Record<string, boolean> }>)[0].selected?.[deathName]
  }, demographyLegend.deathName)
  expect(deathLegendStillHidden).toBe(false)
  await page.locator('#chart-mode-select').selectOption('functional-demography-rates')
  await expect(page.locator('#chart-title')).toContainText('出生率与死亡率')
  await page.locator('#chart-mode-select').selectOption('species-abundance')
  await page.evaluate(() => {
    const instance = (window as Window & { __forestChart: import('echarts').ECharts }).__forestChart
    const series = (instance.getOption().series as Array<{ data: unknown[] }>)[0]
    instance.dispatchAction({ type: 'showTip', seriesIndex: 0, dataIndex: Math.max(0, Math.floor(series.data.length / 2)) })
  })
  await page.waitForTimeout(1_100)
  const tooltipStillVisible = await page.locator('#population-chart').evaluate((element) => Array.from(element.children).some((child) => {
    const html = child as HTMLElement
    return html.style.zIndex === '9999999' && html.style.display !== 'none' && html.style.visibility !== 'hidden' && html.style.opacity !== '0' && Boolean(html.textContent?.trim())
  }))
  expect(tooltipStillVisible).toBe(true)
  await page.keyboard.press('Escape')
  await page.waitForTimeout(50)
  const visibleTooltipsAfterEscape = await page.locator('#population-chart').evaluate((element) => Array.from(element.children).filter((child) => {
    const html = child as HTMLElement
    return html.style.zIndex === '9999999' && html.style.display !== 'none' && html.style.visibility !== 'hidden' && html.style.opacity !== '0' && Boolean(html.textContent?.trim())
  }).map((child) => ({ display: (child as HTMLElement).style.display, visibility: (child as HTMLElement).style.visibility, opacity: (child as HTMLElement).style.opacity, text: child.textContent })))
  expect(visibleTooltipsAfterEscape).toEqual([])
  expect(Math.abs(parseFloat(await page.locator('#chart-mode-select').evaluate((element) => getComputedStyle(element).fontSize)) - chartTitleFontSize)).toBeLessThan(0.1)

  const sliders = page.locator('[data-allocation]')
  await expect(sliders).toHaveCount(3)
  await expect(page.locator('#allocation-total')).toHaveCount(0)
  const allocationGridBox = await page.locator('[data-allocation-grid]').boundingBox()
  const carbonFlowBox = await page.locator('.workspace-strategy .carbon-flow').boundingBox()
  expect(allocationGridBox).not.toBeNull()
  expect(carbonFlowBox).not.toBeNull()
  expect(carbonFlowBox!.y - (allocationGridBox!.y + allocationGridBox!.height)).toBeLessThan(35)
  const sliderBoxes = await sliders.evaluateAll((elements) => elements.map((element) => element.getBoundingClientRect().toJSON()))
  expect(Math.max(...sliderBoxes.map((box) => box.y)) - Math.min(...sliderBoxes.map((box) => box.y))).toBeLessThan(12)
  for (const slider of await sliders.all()) await expect(slider).toBeInViewport()

  await expect(page.locator('#edit-layout-button')).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('[data-window-drag]')).toHaveCount(0)
  await page.locator('#edit-layout-button').click()
  await expect(page.locator('#edit-layout-button')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('[data-window-drag]').first()).toBeVisible()
  const strategyTitle = page.locator('[data-panel-id="strategy"] .workspace-titlebar')
  const beforeDrag = await strategyPanel.boundingBox()
  const titleBox = await strategyTitle.boundingBox()
  expect(beforeDrag).not.toBeNull()
  expect(titleBox).not.toBeNull()
  await page.mouse.move(titleBox!.x + 80, titleBox!.y + 18)
  await page.mouse.down()
  await page.mouse.move(titleBox!.x - 70, titleBox!.y + 65, { steps: 5 })
  await page.mouse.up()
  const afterDrag = await strategyPanel.boundingBox()
  expect(afterDrag).not.toBeNull()
  expect(afterDrag!.x).not.toBeCloseTo(beforeDrag!.x, 0)
  await page.locator('#edit-layout-button').click()
  const afterEditing = await strategyPanel.boundingBox()
  expect(afterEditing!.x).toBeCloseTo(afterDrag!.x, 0)

  await page.locator('#report-button').click()
  const reportCard = page.locator('.report-card')
  const reportBody = page.locator('.report-scroll-body')
  await expect(reportCard).toBeVisible()
  const reportBox = await reportCard.boundingBox()
  expect(reportBox!.height).toBeLessThanOrEqual(page.viewportSize()!.height - 20)
  expect(await reportBody.evaluate((element) => element.scrollHeight >= element.clientHeight)).toBe(true)
  await page.locator('#continue-button').click()
})

test('map query is temporary and detailed statistics open on demand', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('forest-tutorial-completed', 'true'))
  await page.goto('/')
  await chooseScenarioAndAdvance(page, 'sparse')
  await finishSetup(page)
  await page.locator('#pause-button').click()
  await page.locator('[data-speed="4"]').click()
  await expect.poll(async () => Number((await page.locator('#game-time').textContent())?.match(/[\d.]+/)?.[0] ?? 0), { timeout: 15_000 }).toBeGreaterThanOrEqual(3)
  await page.locator('#pause-button').click()
  const selectedAtYear = Number((await page.locator('#game-time').textContent())?.match(/[\d.]+/)?.[0] ?? 0)

  const query = page.locator('#map-query-popover')
  await expect(query).toBeHidden()
  await page.locator('#properties-button').click()
  const oldestVisibleId = await page.locator('#property-table-body [data-property-id]').evaluateAll((rows) => Math.min(...rows.map((row) => Number((row as HTMLElement).dataset.propertyId))))
  await page.locator(`#property-table-body [data-property-id="${oldestVisibleId}"]`).click()
  await expect(query).toBeVisible()
  await page.locator('#chart-mode-select').selectOption('selected')
  await page.waitForTimeout(900)
  const selectedHistoryRange = await page.evaluate(() => {
    const instance = (window as Window & { __forestChart: import('echarts').ECharts }).__forestChart
    const option = instance.getOption() as { xAxis: Array<{ min?: number }>; series: Array<{ data: Array<[number, number]> }> }
    return { min: option.xAxis[0].min, first: option.series[0].data[0]?.[0], last: option.series[0].data.at(-1)?.[0], points: option.series[0].data.length }
  })
  expect(selectedHistoryRange.points).toBeGreaterThan(1)
  expect(selectedHistoryRange.first).toBeLessThan(selectedAtYear)
  expect(selectedHistoryRange.min).toBe(selectedHistoryRange.first)
  expect(selectedHistoryRange.last).toBeGreaterThanOrEqual(selectedAtYear - 0.6)
  await query.locator('.inspection-details summary').click()
  await expect(query.locator('.inspection-details')).toHaveAttribute('open', '')
  await page.waitForTimeout(650)
  await expect(query.locator('.inspection-details')).toHaveAttribute('open', '')
  await page.keyboard.press('Escape')
  await expect(query).toBeHidden()

  await page.locator('#properties-button').click()
  await page.locator('#property-table-body [data-property-id]').first().click()
  await expect(query).toBeVisible()
  await page.locator('[data-panel-id="strategy"]').click({ position: { x: 8, y: 8 } })
  await expect(query).toBeHidden()

  await page.locator('#properties-button').click()
  await page.locator('#property-table-body [data-property-id]').first().click()
  await expect(query).toBeVisible()
  const canvas = page.locator('#game-root canvas')
  const canvasBox = await canvas.boundingBox()
  expect(canvasBox).not.toBeNull()
  await canvas.click({ position: { x: canvasBox!.width * 0.82, y: canvasBox!.height * 0.82 }, force: true })
  await expect(query).toBeVisible()
  await expect(query.locator('#selected-title')).not.toHaveText('点击一个个体或空地')
  await page.locator('[data-panel-id="strategy"]').click({ position: { x: 8, y: 8 } })
  await expect(query).toBeHidden()

  await expect(page.locator('[data-panel-id="statistics"] .metric-grid')).toHaveCount(0)
  await expect(page.locator('#population-chart')).toBeVisible()
  await expect(page.locator('#expand-statistics-button')).toBeVisible()
  await expect(page.locator('#statistics-detail')).toBeVisible()
  await page.locator('#expand-statistics-button').click()
  await expect(page.locator('#statistics-detail')).toBeVisible()
  await expect(page.locator('[data-panel-id="statistics"]')).toHaveAttribute('data-maximized', '')
  await expect(page.locator('#chart-mode-select option[value="composition"]')).toHaveCount(1)
  await expect(page.locator('#chart-mode-select option[value="carbon"]')).toHaveCount(1)
  await expect(page.locator('#chart-mode-select option[value="functional-abundance"]')).toHaveCount(1)
  await expect(page.locator('#chart-mode-select option[value="functional-demography-counts"]')).toHaveCount(1)
  await expect(page.locator('#chart-mode-select option[value="functional-demography-rates"]')).toHaveCount(1)
})

test('density controls cover 10–400 nonlinearly without starting a 10,000-tree game', async ({ page }) => {
  await page.goto('/')
  await chooseScenarioAndAdvance(page, 'colonization')
  await expect(page.locator('#density-input')).toHaveAttribute('min', '10')
  await expect(page.locator('#density-input')).toHaveAttribute('max', '400')
  await expect(page.locator('#density-input')).toHaveValue('10')
  await expect(page.locator('#density-total')).toContainText('256 个体')

  await page.locator('#density-slider').fill('50')
  await expect(page.locator('#density-input')).not.toHaveValue('205')
  await page.locator('#density-input').fill('400')
  await expect(page.locator('#density-total')).toContainText('10,006 个体')
})

test('tutorial replay and font size remain available from the system bar', async ({ page }) => {
  await page.goto('/')
  await chooseScenarioAndAdvance(page, 'sparse')
  await finishSetup(page)
  await expect(page.locator('#tutorial-modal')).toBeVisible()
  await page.locator('#tutorial-skip').click()

  const mapBeforeFontChange = await page.locator('#game-root').boundingBox()
  const eventBeforeFontChange = await page.locator('.map-event-strip').boundingBox()

  const largeFontButton = page.locator('button[data-font-size="large"]')
  await largeFontButton.click()
  await expect(largeFontButton).toHaveClass(/active/)
  await expect(largeFontButton).toHaveAttribute('aria-pressed', 'true')
  expect(await page.evaluate(() => document.documentElement.dataset.fontSize)).toBe('large')
  expect(await page.evaluate(() => localStorage.getItem('forest-font-size'))).toBe('large')
  const mapAfterFontChange = await page.locator('#game-root').boundingBox()
  const eventAfterFontChange = await page.locator('.map-event-strip').boundingBox()
  expect(Math.abs(mapAfterFontChange!.width - mapBeforeFontChange!.width)).toBeLessThanOrEqual(2)
  expect(Math.abs(mapAfterFontChange!.height - mapBeforeFontChange!.height)).toBeLessThanOrEqual(2)
  expect(eventAfterFontChange!.height).toBeCloseTo(eventBeforeFontChange!.height, 0)

  await page.locator('#help-button').click()
  await expect(page.locator('#tutorial-modal')).toBeVisible()
  await expect(page.locator('#tutorial-body')).toContainText('按住鼠标右键拖动')
  for (let step = 0; step < 6; step += 1) {
    await page.waitForTimeout(220)
    const focus = page.locator('.tutorial-focus')
    await expect(focus).toHaveCount(1)
    const focusBox = await focus.boundingBox()
    const spotlightBox = await page.locator('#tutorial-spotlight').boundingBox()
    const tutorialCardBox = await page.locator('.tutorial-card').boundingBox()
    expect(focusBox).not.toBeNull()
    expect(spotlightBox).not.toBeNull()
    expect(tutorialCardBox).not.toBeNull()
    expect(spotlightBox!.x).toBeLessThanOrEqual(focusBox!.x)
    expect(spotlightBox!.y).toBeLessThanOrEqual(focusBox!.y)
    expect(right(spotlightBox!)).toBeGreaterThanOrEqual(right(focusBox!))
    expect(bottom(spotlightBox!)).toBeGreaterThanOrEqual(bottom(focusBox!))
    expect(intersectionArea(tutorialCardBox!, focusBox!)).toBe(0)
    await page.locator('#tutorial-next').click()
  }
  await expect(page.locator('#tutorial-modal')).toBeHidden()

  await page.reload()
  expect(await page.evaluate(() => document.documentElement.dataset.fontSize)).toBe('large')
})

test('narrow screens use a map with bottom workspace drawers', async ({ page }) => {
  await page.setViewportSize({ width: 800, height: 900 })
  await page.addInitScript(() => localStorage.setItem('forest-tutorial-completed', 'true'))
  await page.goto('/')
  await chooseScenarioAndAdvance(page, 'sparse')
  await finishSetup(page)
  await expect(page.locator('[data-panel-id="map"]')).toBeVisible()
  await expect(page.locator('[data-panel-id="strategy"]')).not.toHaveAttribute('data-mobile-open', '')
  await page.locator('[data-workspace-open="strategy"]').click()
  await expect(page.locator('[data-panel-id="strategy"]')).toHaveAttribute('data-mobile-open', '')
  await page.locator('.workspace-taskbar [data-workspace-open="statistics"]').click()
  await expect(page.locator('[data-panel-id="statistics"]')).toHaveAttribute('data-mobile-open', '')
  await expect(page.locator('[data-panel-id="strategy"]')).not.toHaveAttribute('data-mobile-open', '')
})

test('Canvas fallback keeps marker coordinates aligned while zooming', async ({ page }) => {
  const browserErrors: string[] = []
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await page.addInitScript(() => localStorage.setItem('forest-tutorial-completed', 'true'))
  await page.goto('/?renderer=canvas')
  await chooseScenarioAndAdvance(page, 'sparse')
  await finishSetup(page)
  const canvas = page.locator('#game-root canvas')
  await expect(canvas).toBeVisible()
  expect(await canvas.evaluate((element) => Boolean((element as HTMLCanvasElement).getContext('2d')))).toBe(true)
  const box = await canvas.boundingBox()
  expect(box).not.toBeNull()
  await canvas.hover({ position: { x: box!.width * 0.45, y: box!.height * 0.55 } })
  await page.mouse.wheel(0, -500)
  await expect(page.locator('#map-x-tick-0')).not.toHaveText('0')
  const tickBeforePan = await page.locator('#map-x-tick-0').textContent()
  await page.mouse.move(box!.x + box!.width * 0.5, box!.y + box!.height * 0.5)
  await page.mouse.down({ button: 'right' })
  await page.waitForTimeout(150)
  await expect(canvas).toHaveClass(/is-panning/)
  await page.mouse.move(box!.x + box!.width * 0.62, box!.y + box!.height * 0.5, { steps: 5 })
  await page.mouse.up({ button: 'right' })
  await expect(canvas).not.toHaveClass(/is-panning/)
  await expect(page.locator('#map-x-tick-0')).not.toHaveText(tickBeforePan ?? '')
  await page.locator('#reset-map-button').click()
  await expect(page.locator('#map-x-tick-0')).toHaveText('0')
  expect(browserErrors).toEqual([])
})

test('a 10,000-individual map stays interactive at at least 30 FPS', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('forest-tutorial-completed', 'true'))
  await page.goto('/')
  await chooseScenarioAndAdvance(page, 'closed')
  await page.locator('#density-input').fill('400')
  await finishSetup(page)
  await expect(page.locator('#game-root canvas')).toBeVisible({ timeout: 15_000 })

  const fps = await page.evaluate(() => new Promise<number>((resolve) => {
    const frames: number[] = []
    const sample = (time: number) => {
      frames.push(time)
      if (frames.length < 61) requestAnimationFrame(sample)
      else resolve((frames.length - 1) / ((frames.at(-1)! - frames[0]) / 1000))
    }
    requestAnimationFrame(sample)
  }))
  expect(fps).toBeGreaterThanOrEqual(30)

  const understoryLayer = page.locator('[data-view-layer="understory"]')
  await understoryLayer.scrollIntoViewIfNeeded()
  await understoryLayer.click()
  await expect(page.locator('[data-view-layer="understory"]')).toHaveClass(/active/)
  await page.locator('#properties-button').click()
  await expect(page.locator('#property-page-status')).toContainText('10,000 条')
  expect(await page.locator('#property-table-body tr').count()).toBeLessThanOrEqual(150)
  const firstRange = await page.locator('#property-page-status').textContent()
  await page.locator('#property-page-next').click()
  await expect(page.locator('#property-page-status')).not.toHaveText(firstRange ?? '')
  expect(await page.locator('#property-table-body tr').count()).toBeLessThanOrEqual(150)
  await page.locator('#close-properties-button').click()

  await page.locator('#pause-button').click()
  await page.locator('[data-speed="4"]').click()
  await page.waitForTimeout(300)
  const runningFps = await page.evaluate(() => new Promise<number>((resolve) => {
    const frames: number[] = []
    const sample = (time: number) => {
      frames.push(time)
      if (frames.length < 61) requestAnimationFrame(sample)
      else resolve((frames.length - 1) / ((frames.at(-1)! - frames[0]) / 1000))
    }
    requestAnimationFrame(sample)
  }))
  expect(runningFps).toBeGreaterThanOrEqual(30)
})
